name: build graalvm
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - graalvm/**
jobs:
  graalvm-ce:
    name: "graalvm-ce-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - jdk8
        - jdk11
        - jdk17
        - jdk21
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./java/graalvm
          file: ./java/graalvm/Dockerfile.ce-${{ matrix.tag }}
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/ccarney16/pterodactyl-images:graalvm-ce-${{ matrix.tag }}
  graalvm:
    name: "graalvm-${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
        - jdk25
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./java/graalvm
          file: ./java/graalvm/Dockerfile.${{ matrix.tag }}
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/ccarney16/pterodactyl-images:graalvm-${{ matrix.tag }}