name: build java
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - java/**
jobs:
  push:
    name: "java_${{ matrix.tag.group }}.${{ matrix.tag.version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - { version: jdk11, group: corretto }
          - { version: jdk11, group: deployable }
          - { version: jdk17, group: deployable }
          - { version: jdk21, group: deployable }
          - { version: jdk17, group: temurin }
          - { version: jdk21, group: temurin }
          - { version: jdk23, group: temurin }
          - { version: jdk24, group: temurin }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./java
          file: ./java/${{ matrix.tag.group }}/Dockerfile.${{ matrix.tag.version }}
          platforms: linux/amd64
          push: true
          tags: |
            docker.io/ccarney16/pterodactyl-images:${{ matrix.tag.version }}-${{ matrix.tag.group }}
